# Generated by Django 4.2 on 2023-04-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('building_limit', models.IntegerField()),
                ('default_building', models.CharField(max_length=111)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='r2_gc_planner.province')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('growth', models.IntegerField()),
                ('food', models.IntegerField()),
                ('public_order', models.IntegerField()),
                ('public_order_all', models.IntegerField()),
                ('loc_commerce_income', models.IntegerField()),
                ('mar_commerce_income', models.IntegerField()),
                ('subsistence_income', models.IntegerField()),
                ('agriculture_income', models.IntegerField()),
                ('lstock_income', models.IntegerField()),
                ('industry_income', models.IntegerField()),
                ('culture_income', models.IntegerField()),
                ('bonus_all', models.IntegerField()),
                ('bonus_commerce', models.IntegerField()),
                ('bonus_mar_commerce', models.IntegerField()),
                ('bonus_agriculture', models.IntegerField()),
                ('bonus_lstock', models.IntegerField()),
                ('bonus_industry', models.IntegerField()),
                ('bonus_culture', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='r2_gc_planner.faction')),
            ],
        ),
    ]
