# Generated by Django 4.2 on 2023-04-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='agriculture_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_agriculture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_commerce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_industry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_lstock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='bonus_mar_commerce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='culture_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='r2_gc_planner.faction'),
        ),
        migrations.AlterField(
            model_name='building',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='growth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='industry_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='loc_commerce_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='lstock_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='mar_commerce_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='public_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='public_order_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='subsistence_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='r2_gc_planner.province'),
        ),
    ]
