# Generated by Django 4.2 on 2023-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0006_rename_building_limit_city_building_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
