# Generated by Django 4.2 on 2023-04-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0007_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='icon',
            field=models.ImageField(default='img/building_logos/slum_default.png', upload_to='static/img/building_logos'),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_icon',
            field=models.ImageField(default='img/faction_logos/rome.png', upload_to='static/img/faction_logos'),
        ),
        migrations.AlterField(
            model_name='city',
            name='building_slots',
            field=models.IntegerField(default=6),
        ),
    ]
