# Generated by Django 4.2 on 2023-04-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0009_alter_building_icon_alter_faction_faction_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='building_slots',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
