# Generated by Django 4.2 on 2023-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0010_alter_city_building_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='building_slots',
            field=models.IntegerField(default=6),
        ),
    ]
