# Generated by Django 4.2 on 2023-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0011_alter_city_building_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='trade_resources',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
