# Generated by Django 4.2 on 2023-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0012_alter_building_trade_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bonus_food',
            field=models.IntegerField(default=0),
        ),
    ]
