# Generated by Django 4.2 on 2023-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2_gc_planner', '0013_building_bonus_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='icon',
            field=models.ImageField(default='r2_gc_planner/static/r2_gc_planner/img/building_logos/slum_default.png', upload_to='r2_gc_planner/static/r2_gc_planner/img/building_logos'),
        ),
        migrations.AlterField(
            model_name='building',
            name='trade_resources',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_icon',
            field=models.ImageField(default='r2_gc_planner/static/r2_gc_planner/img/faction_logos/rome.png', upload_to='r2_gc_planner/static/r2_gc_planner/img/faction_logos'),
        ),
    ]
